#!/bin/sh
seclists="/share/wordlists/SecLists/Discovery/Web-Content/"
alias dirbc="gobuster dir -q -k -t 50 -e -w /share/wordlists/content/common.txt -u"
alias dirba="gobuster dir -q -k -t 50 -e -w /share/wordlists/content/all_content_discovery.txt -u"
alias dirbf="gobuster dir -q -k -t 50 -e -w /share/wordlists/content/fuzz.txt -u"


todate=$(date +"%Y-%m-%d")
foldername=recon-$todate
mkdir $foldername


WAYBACKFILES="./$foldername/waybackurls.txt"
touch $WAYBACKFILES
WAYBACKFILEUSEFUL="$WAYBACKFILES-useful.txt"
touch $WAYBACKFILEUSEFUL

# Let's go through / over all hosts
MEGPATH="./$foldername/meg/"
mkdir $MEGPATH
meg -c 100 / $1 $MEGPATH

cat $1 | waybackurls | tee -a $WAYBACKFILES
cat waybackurls.txt | sed '/^$/d' | sed -e '/png\|PNG\|gif\|GIF\|jpg\|JPG\|woff\|WOFF\|css\|CSS\|pdf\|PDF\|svg\|SVG\|ttf\|TTF/d' | unfurl -u format "%s://%d%:%P%p" | tee $WAYBACKFILEUSEFUL

FILES="./$foldername/files-all.txt"
touch $FILES
FILESUSEFUL="$FILES-useful.txt"
touch $FILESUSEFUL

for LINE in $(cat $1 | shuf); do
        echo $LINE
        SIZE=$(curl -so /dev/null $LINE/aaaaaaaaaaaaa -w '%{size_download}')
        ffuf -w $seclists/common.txt -u $LINE/FUZZ -fs $SIZE
        #gobuster dir -q -k -r -t 50 -e -w $seclists/common.txt -u $LINE | tee -a $FILES
        #gobuster dir -q -k -r -t 50 -e -w $seclists/oracle.txt -u $LINE | tee -a $FILES
        #gobuster dir -q -k -r -t 50 -e -w $seclists/sap.txt -u $LINE | tee -a $FILES
        #gobuster dir -q -k -r -t 50 -e -w $seclists/nginx.txt -u $LINE | tee -a $FILES
        #gobuster dir -q -k -r -t 50 -e -w $seclists/jboss.txt -u $LINE | tee -a $FILES
        #gobuster dir -q -k -r -t 50 -e -w $seclists/apache.txt -u $LINE | tee -a $FILES
        #gobuster dir -q -k -r -t 50 -e -w $seclists/OracleAppServer.fuzz.txt -u $LINE | tee -a $FILES
        #gobuster dir -q -k -r -t 50 -e -w $seclists/ApacheTomcat.fuzz.txt -u $LINE | tee -a $FILES
done;

cat files.txt | grep "(Status: 200)" | sed -e 's/ .*$//g' | tee -a $FILESUSEFUL

